sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
notifications:
  email: false
before_script: chmod +x script/coverage
after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
